[package]
name = "NftLiquidityLayer"
version = "0.3.0"

[dependencies]
NftProtocol = { git = "https://github.com/Origin-Byte/nft-protocol", rev = "0.3.0" }
Sui = { git = "https://github.com/MystenLabs/sui.git", subdir = "crates/sui-framework", rev = "devnet-0.9.0" }

[addresses]
nft_liquidity_layer = "0x0"
# nft_protocol = "0xe6d6f01725d469b7b04d9905e6b3151e8c4264cb"
